import React from "react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useGetStrings from "../front/hooks/useGetStrings.hook";
import Link from "next/link";
import IconSelector from "../front/components/ui/IconSelector";

const Home: NextPage = () => {
    const strings = useGetStrings("mainPage");
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Lobster&display=optional"
                    rel="stylesheet"
                />
            </Head>
            <header className={styles.header}>
                <div className={styles.ribbon}>
                    <p className={styles.ribbonText}>{strings["ribbonText"]}</p>
                </div>
                <div className={styles.logoAndButtons}>
                    <div className={styles.logoContainer}>
                        <h1 className={styles.headerTitleText}>
                            {strings["title"]}
                        </h1>
                    </div>
                    <div className={styles.buttonsContainer}>
                        <Link href={"/"}>
                            <div className={styles.headerButton}>
                                <p className={styles.headerButtonText}>
                                    {strings["homeButtonText"]}
                                </p>
                            </div>
                        </Link>
                        <div className={styles.headerButton}>
                            <p className={styles.headerButtonText}>
                                {strings["aboutProjectButtonText"]}
                            </p>
                        </div>
                        <div className={styles.headerButton}>
                            <p className={styles.headerButtonText}>
                                {strings["contribute"]}
                            </p>
                        </div>
                    </div>
                </div>
            </header>
            <main className={styles.main}>
                <div className={styles.fistMainContainer}>
                    <IconSelector />
                </div>
                <div className={styles.secondMainContainer}></div>
            </main>
            <footer className={styles.footer}>
            </footer>
        </div>
    );
};

export const getStaticProps: GetStaticProps = async (context) => {
    return {
        props: {}
    };
};

export default Home;
