import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <div className={styles.ribbon}>
                    <p className={styles.ribbonText}>{"•  ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER  •   ANOTHER REACT NATIVE SVG PARSER"}</p>
                </div>
                <div className={styles.logoAndButtons}>
                    <div className={styles.logoContainer}>

                    </div>
                    <div className={styles.buttonsContainer}>
                        <div className={styles.headerButton}>

                        </div>
                        <div className={styles.headerButton}>

                        </div>
                        <div className={styles.headerButton}>

                        </div>
                    </div>
                </div>
            </header>
            <main className={styles.main}>
            </main>
            <footer className={styles.footer}>
            </footer>
        </div>
    );
};

export default Home;
